### ISSUE TITLE
Can it catch all system call in Linux on Xen? Which version  can it support?

### ISSUE THREAD

**Issue by Badangel** [tklengyel/guestrace#3]
I want to catch all the system call real-time  outof guestVM(Ubuntu) on xen and then use them to do other detection, it can work?
And if I use it, I should install which version software such as Xen、libvmi、rekall and so on.
Now I use ubuntu 16.04LTS(linux-4.4.0-57),libvmi in github(no release but recent), xen 4.6.0. Can it support?
I see it code by python, but the pyvmi of libvmi is not work recently.
Hope your reply! Thank you!

**Comment by tklengyel** [comment]
This repository is just a mirror of https://www.flyn.org/projects/guestrace/index.html, please send questions regarding it to them, I do not support guestrace.
